name: CI Pipeline for Finance Tracker

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build Docker Image
        run: |
          docker build -t teja5gowda/Finance-Tracker .

      - name: Run Tests
        run: |
          docker run teja5gowda/Finance-Tracker pytest tests/

  docker-push:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Docker Login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker Image to Docker Hub
        run: |
          docker push yourusername/finance-tracker
